#! /bin/sh
exiftool -all= "$5"
exiftool -Make="Konishiroku Photo Industry Co., Ltd." -Model="Konica IIIA" -LensMake="Konishiroku Photo Industry Co., Ltd." -LensModel="Konishiroku Hexanon 1:1.8 50mm" -FocalLength=50 -FocalLengthIn35mmFormat=50 -Artist="mitsugu oyama" -Copyright="Copyright (c) $1 mitsugu oyama All Rights Reserved." -CreateDate="$2" -DateTimeOriginal="$2" -ISO="$3" -UserComment="$4 I forgot to record time, LV, shutter speed and aperture." "$5"

