#! /bin/sh
exiftool -all= "$7"
exiftool -Make="Asahi Optical Co., Ltd." -Model="PENTAX MX" -LensMake="RICOH IMAGING COMPANY, LTD." -LensModel="HD PENTAX-FA 35mm F2" -FocalLength=35 -FocalLengthIn35mmFormat=35 -Artist="mitsugu oyama" -Copyright="Copyright (c) $1 mitsugu oyama All Rights Reserved."  -CreateDate="$2" -DateTimeOriginal="$2" -FNumber="$3" -ExposureTime="$4" -ISO="$5" -UserComment="$6" "$7"

