#! /bin/sh
#
# Usage :
#   wm filename location
#
#     filename : file Name
#     location : Location to display Exif data
#                Specify the argument of ImageMagick's gravity option.
#                NorthWest, North, NorthEast, East, SouthEast, South, SouthWest
#
copyright="Mitsugu Oyama \( OrzBruford \)"
#copyright="Mitsugu Oyama"
date=`exiftool -s -DateTimeOriginal -T $1`
make=`exiftool -s -Make -T $1`
camera=`exiftool -s -Model -T $1`
#lens=`exiftool -s -LensID -T $1`
lens=`exiftool -s -LensModel -T $1`
iso=`exiftool -s -ISO -T $1`
fnumber=`exiftool -s -FNumber -T $1`
ss=`exiftool -s -ShutterSpeed -T $1`
soft=`exiftool -s -Software -T $1`
com=`exiftool -s -UserComment -T $1`
font=Helvetica
#font=./Mplus2-Light.ttf
#size="740x166"
#fontsize=12
#splice=8x

## CAMEDIA
size="264x192"
fontsize=14
splice=8x4

## PENTAX MX
#size="264x128"
#fontsize=10
#splice=4x4


convert -font $font \
  -size "$size" \
  -splice "$splice" \
  -fill "#FFFFFF" \
  -background none \
  -pointsize "$fontsize" \
  label:"\nCopyright : $copyright\nDate and Time : $date\nMaker : $make\nCamera : $camera\nLens : $lens\nISO : $iso\nF Number : $fnumber\nShutter Speed : $ss\nSoftware : $soft\nComment : $com" \
  hoge.png

convert "$1" hoge.png -gravity "$2" -compose over -composite "$1.jpg"
rm hoge.png

