#! /bin/sh
#
# Usage :
#   wm filename location
#
#     filename : file Name
#     location : Location to display Exif data
#                Specify the argument of ImageMagick's gravity option.
#                NorthWest, North, NorthEast, East, SouthEast, South, SouthWest
#
copyright="Mitsugu Oyama"
title="$3"
date=`exiftool -s -DateTimeOriginal -T $1`
make=`exiftool -s -Make -T $1`
camera=`exiftool -s -Model -T $1`
#lens=`exiftool -s -LensID -T $1`
lens=`exiftool -s -LensModel -T $1`
iso=`exiftool -s -ISO -T $1`
fnumber=`exiftool -s -FNumber -T $1`
ss=`exiftool -s -ShutterSpeed -T $1`
soft=`exiftool -s -Software -T $1`
font=Helvetica

## Huawei
#size="1280x768"
#fontsize=64

## PENTAX *ist DL2
#size="840x576"
#fontsize=48

## PENTAX KP
size="1280x702"
fontsize=63

convert -font $font \
  -size "$size" \
  -splice 32x \
  -fill "#FFFFFF" \
  -background none \
  -pointsize "$fontsize" \
  label:"\nCopyright : $copyright\nTitle : ${title}\nDate and Time : $date\nMaker : $make\nCamera : $camera\nLens : $lens\nISO : $iso\nF Number : $fnumber\nShutter Speed : $ss\nSoftware : $soft" \
  hoge.png

convert "$1" hoge.png -gravity "$2" -compose over -composite "$1.jpg"
rm hoge.png

